### ISSUE TITLE
Need of Documentation 

### ISSUE THREAD

**Issue by chinmayk26** [sahilm-10/OnlineFoodDelivery#2]
Brief description of the Project

**Comment by chinmayk26** [comment]
@sahilm-10 can you please assign the issue

**Comment by sahilm-10** [comment]
Sure !

**Comment by chinmayk26** [comment]
[README.md](https://github.com/sahilm-10/OnlineFoodDelivery/files/9727195/README.md)

**Comment by chinmayk26** [comment]
Can you check the details and merge it

**Comment by chinmayk26** [comment]
I have added the Documentation. Kindly check and merge it

**Comment by sahilm-10** [comment]
Done !
